name: Deploy to Azure App Service without ZIP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy using az webapp deploy (non-ZIP)
      run: |
        az webapp deploy \
          --name FetusApp-Dev \
          --resource-group fetusapp-development \
          --src-path . \
          --type static
