name: Deploy to Azure App Service without ZIP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Zip app contents
      run: |
        zip -r app.zip .

    - name: Deploy zip package to Azure App Service
      run: |
        az webapp deploy \
          --name FetusApp-Dev \
          --resource-group fetusapp-development \
          --src-path app.zip \
          --type zip
