name: Deploy Flask App to Azure App Service (No Oryx)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip application
      run: |
        zip -r app.zip .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deploy \
          --resource-group groupname-dev \
          --name NameApp-Dev \
          --src-path app.zip \
          --type zip

    # - name: Deploy to Azure Web App
    #   run: |
    #     az webapp deploy \
    #       --resource-group fetusapp-development \
    #       --name FetusApp-Dev \
    #       --src-path app.zip \
    #       --type zip
